Feat/BE-14-implement-Video-call-feature-Agora-token-generator
zurichat/zc_core pull request #609
Opened 2022-12-09 18:48 UTC by taiwonaf

- Make the uid a querry parameter
- Removed the ability to generate token using uid

2022-12-10 13:00 UTC, billmal071 commented
@NwokoyeChigozie @Aminujb @UfiairENE Please help review and merge.

2022-12-10 20:46 UTC, Aminujb requested changes
Just this minor change

2022-12-10 20:46 UTC, Aminujb commented on agora/rtctoken.go
> +		// 	}
If these lines are not useful, you need to take them out.

2022-12-10 20:46 UTC, Aminujb commented on agora/rtctoken.go
> +		// 	return rtcToken,
These too need to go if there is need for it.

2022-12-11 06:19 UTC, Aminujb approved these changes
LGTM!

2022-12-11 06:19 UTC, merged